env:
    # Config
    CONFIG: config.sh
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Nico17042020/TeamWin-CI/twrp/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Nico17042020/TeamWin-CI/twrp/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Nico17042020/TeamWin-CI/twrp/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Nico17042020/TeamWin-CI/twrp/scripts/upload.sh)"
